language: node_js

node_js:
  - 8.11.2

deploy:
  - provider: script
    script: npm run start

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: before test
      script: npm run before:test
    - stage: e2e
      script: npm run e2e
