language: node_js

node_js:
  - 8.11.2

sudo: required

addons:
  chrome: stable

jobs:
  include:
    - stage: before test
      script: npm run before:test
    - stage: e2e
      script: npm run e2e
